services:
  postgres:
    image: 'postgres:16.1'
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
    ports:
      - '5432:5432'
    restart: unless-stopped